### ISSUE TITLE
项目管理咨询

### ISSUE THREAD

**Issue by bicijinlian** [dotnetcore/Home#60]
各位大侠：这里很多项目，都不咋更新了，整体项目管理也比较低。是不准备维护了么？还是说.net已经没落了？有些伤心

**Comment by alexinea** [comment]
Instead of being filled with pessimism because of a moment of trough, we remain confident in the future of .NET.

At present, there are relatively few new open source projects in the Chinese developer community, and the high-quality projects are even more lackluster. Therefore, there are currently no new member projects in the community to join us.

We will continue to search for new outstanding projects and actively seek them to join the NCC community.

Most importantly, with the end of the COVID19 epidemic control and the weakening of the impact of the virus on everyone, the online activity of the NCC community will gradually increase. Of course, everyone takes care of the community in their spare time, so it is more or less impossible to maintain around the clock like full-time community maintainers or enterprise open source project communities.

We believe that as .NET gets better, so does NCC.

一緒に頑張りましょう (#^.^#) 。

**Comment by DanceGay** [comment]
打倒ncc邪教！支持tony老师！支持npoi！乌克兰万岁！

**Comment by alexinea** [comment]
According to the NCC Community Political Barriers Reg 2020 (CPBR/2020), I have marked the above comment as spam.  

If @DanceGay violates the community regulations again by submitting spam messages under the NCC organization or any of its member projects, appropriate measures WILL BE taken to block his or her activities.

This is a serious warning.
